### ISSUE TITLE
Codeserver Icon doesn't appear 

### ISSUE THREAD

**Issue by nskrjabins** [aws-samples/amazon-sagemaker-codeserver#12]
So I've followed this [guide](https://aws.amazon.com/blogs/machine-learning/host-code-server-on-amazon-sagemaker/) to set up coderserver on SageMaker Studio. 

The codeserver icon doesn't appear but I can still access the codeserver by slightly changing the URL - 
**[domain-id].studio.[aws-region].sagemaker.aws/jupyter/default/codeserver**. Screenshot below.

<img width="1438" alt="codeserver" src="https://user-images.githubusercontent.com/60360098/205900667-39400322-3ca3-42b2-be08-5ceeaee5e5b5.png">

I suspect that icon fails to attach because of the new SageMaker Studio UI. Screenshot below.

<img width="1440" alt="new UI" src="https://user-images.githubusercontent.com/60360098/205901047-cf11efe9-0e2f-429d-98a0-f4df657c26e4.png">

I noticed the new UI on 5th December 22 which is when I tried to set up the codeserver on SageMaker Studio.

**Comment by giuseppeporcelli** [comment]
Hi @nskrjabins, thanks for reaching out and for opening this issue.

We are aware of this behavior, and we will provide an update soon.
In the meantime, the workaround you have identified is what we would suggest doing to continue accessing code-server.

I'll keep this issue open for updates.

**Comment by nskrjabins** [comment]
@giuseppeporcelli Any ETA on when this will be fixed?

**Comment by massi-ang** [comment]
Any ETA?

**Comment by Almenon** [comment]
It appears for me now with the latest version of the studio install script.

**Comment by wiliscavalcante** [comment]
This didn't work for me, the code server icon still doesn't appear in the UI

**Comment by orangewise** [comment]
I also don't see the icon, changing the url works (JL3).

**Comment by orangewise** [comment]
After updating the domain and setting the default SageMakerImageArn to "arn:aws:sagemaker:eu-central-1:936697816551:image/jupyter-server-3" the icon shows up...

**Comment by giuseppeporcelli** [comment]
Hi,
I'm happy to share that this issue is solved by upgrading to the latest version (5.1000.0) of Amazon SageMaker Studio (JupyterServer). Then, you just need to re-install code-server as explained in this repo.

The code-server icon will appear in the launcher as expected, as shown below:

<img width="1449" alt="Screenshot 2023-02-02 at 17 46 18" src="https://user-images.githubusercontent.com/7733029/216619448-95f913dc-3af3-43aa-8ace-a5ad5beaef29.png">

Instructions on how to upgrade Amazon SageMaker Studio are here: https://docs.aws.amazon.com/sagemaker/latest/dg/studio-tasks-update-studio.html

Thanks for your patience.

**Comment by tonyszhang** [comment]
@giuseppeporcelli I think https://github.com/jupyterlab/jupyterlab/releases/tag/v3.6.1 might have broken the icons in studio again.
